-- AlterTable
ALTER TABLE "Evidence" ADD COLUMN IF NOT EXISTS "lat" DOUBLE PRECISION;
ALTER TABLE "Evidence" ADD COLUMN IF NOT EXISTS "lng" DOUBLE PRECISION;
ALTER TABLE "Evidence" ADD COLUMN IF NOT EXISTS "headingDeg" DOUBLE PRECISION;
